#Makefile for Lab 11, Declan Sheehan Cosc320-001
#If you have trouble compiling, it's b/c I was not able to test
#this makefile.
run:
	g++ -std=c++11 -c main.cpp
	g++ -o lab11.exe main.o

rebuild:
	make clean
	make

clean:
	rm -f lab11.exe main.o